---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - unzip
      - python3
      - python3-pip
      - nodejs
      - npm
      - sudo
    state: present

- name: Clean apt cache
  apt:
    autoclean: yes
